baseURL = 'https://telteu.ro/'
DefaultContentLanguage = "en"
title = 'Andrei Telteu'
copyright = "Andrei Telteu 2024"
theme = "diary"

[languages]
    [languages.en]
        weight = 0
        disabled = false
        languageCode = 'en'
        languageDirection = 'ltr'
        languageName = 'English'
    [languages.ro]
        weight = 1
        disabled = false
        languageCode = 'ro'
        languageDirection = 'ltr'
        languageName = 'Română'

[params]
    subtitle = "Coding stuff"
    enableGitalk = false
    enableGiscus = true
    # Twitter Card and Open Graph settings
    enableOpenGraph = true
    enableTwitterCards = true
    title = "AndreiTelteu"
    description = "Andrei Telteu dev blog"

[params.code_block_panel]
    max_lines = 200

[params.giscus]
    data_repo="AndreiTelteu/Telteu.ro-blog"
    data_repo_id="R_kgDONQ0fTQ"    
    data_category="Announcements"
    data_category_id="DIC_kwDONQ0fTc4CkWo_"
    data_mapping="pathname"
    data_strict="1"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"
[languages.ro.params.giscus]
    data_lang="ro"

[taxonomies]
    tag = "tags"
    category = "categories"
[languages.ro.taxonomies]
    eticheta = "etichete"
    categorie = "categorii"


[menu]
[[menu.main]]
    url = "/categories/devops/"
    name = "DevOps"
    weight = 1
[[languages.ro.menu.main]]
    url = "/ro/categorii/devops/"
    name = "DevOps"
    weight = 1

[[menu.main]]
    url = "/categories/golang/"
    name = "GoLang"
    weight = 2
[[languages.ro.menu.main]]
    url = "/ro/categorii/golang/"
    name = "GoLang"
    weight = 2

[[menu.main]]
    url = "/categories/3d-print/"
    name = "3D Print"
    weight = 3
[[languages.ro.menu.main]]
    url = "/ro/categorii/3d-print/"
    name = "3D Print"
    weight = 3

[[menu.main]]
    url = "/categories/raspberry-pi/"
    name = "Raspberry Pi"
    weight = 4
[[languages.ro.menu.main]]
    url = "/ro/categorii/raspberry-pi/"
    name = "Raspberry Pi"
    weight = 4

[[menu.main]]
    url = "/categories/solid-js/"
    name = "Solid JS"
    weight = 5
[[languages.ro.menu.main]]
    url = "/ro/categorii/solid-js/"
    name = "Solid JS"
    weight = 5

[[menu.main]]
    url = "/index.xml"
    name = "RSS Feed"
    weight = 6
[[languages.ro.menu.main]]
    url = "/ro/index.xml"
    name = "Feed RSS"
    weight = 6

[module]
    [[module.imports]]
        path = 'github.com/hugomods/code-block-panel'
    [[module.imports]]
        path = "github.com/hugomods/icons/vendors/bootstrap"
    [[module.imports]]
        path = "github.com/hugomods/images"
    [[module.imports]]
        path = "github.com/hugomods/search"

[markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = "native"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
    home = ['HTML', 'RSS', 'SearchIndex']
